# server environment configuration
uvicorn:
  host: ${UvicornHost}
  port: ${UvicornPort}
  log_level: info
  reload: false
db_connection:
  postgres_user: ${PostgresUser}
  postgres_password: ${PostgresPassword}
  postgres_server: ${PostgresServer}
  postgres_database: ${PosgresDatabase}
api_config:
  title: Simple FastAPI Server
  description: API Documentation for Simple FastAPI Server
  version: v1
  docs_url: /docs
