# server environment configuration
uvicorn:
  host: 0.0.0.0
  port: 8000
  log_level: debug
  reload: true
db_connection:
  postgres_user: postgres
  postgres_password: postgres
  postgres_server: localhost
  postgres_database: app
api_config:
  title: "Simple FastAPI Server"
  description: "API Documentation for Simple FastAPI Server"
  version: v1
  docs_url: /docs
